### ISSUE TITLE
Test-IRMConfiguration -Sender Holly@...onmicrosoft.com failing with error

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#55]
Learning path 4 - Lab 4 - Exercise 1 - Configure Microsoft 365 Message Encryption
Task 1, Step 17

Description of issue

Test-IRMConfiguration -Sender Holly@... fails with the following error. It may be related to the issue in https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/issues/9. 

---
Results : Acquiring RMS Templates ...
- PASS: RMS Templates acquired. Templates available: Highly Confidential \ All Employees, Highly Confidential, Confidential \ All Employees, Confidential - Finance, Highly Confidential - Project - Falcon, Encrypt, Do Not
Forward.
Verifying encryption ...
- FAIL: Failed to verify encryption.
----------------------------------------
Microsoft.Exchange.Data.RightsManagement.RmException: Failed to get publishing license. FailureCode:UnknownFailure. Recoverable:False. ---> Microsoft.Exchange.Data.RightsManagement.RmException: Failed to fetch the adhoc
license handle. FailureCode:UnknownFailure. Recoverable:False. ---> Microsoft.Exchange.Data.RightsManagement.RmException: Creating AdHoc License with empty recipients. FailureCode:UnknownFailure. Recoverable:False.
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.CreateAdhocLicense(IRmEncryptionContext context, Object templateIssuer, EncryptionAlgorithm algo)
--- End of inner exception stack trace ---
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.CreateAdhocLicense(IRmEncryptionContext context, Object templateIssuer, EncryptionAlgorithm algo)
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.GetEncryptionHandle(IRmEncryptionContext context, EncryptionAlgorithm algo)
--- End of inner exception stack trace ---
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.GetEncryptionHandle(IRmEncryptionContext context, EncryptionAlgorithm algo)
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.InternalPrepareForEncryption(IRmEncryptionContext encryptionContext)
at Microsoft.Exchange.Data.RightsManagement.MSIPC.MsipcClientV2.PrepareForEncryption(IRmEncryptionContext encryptionContext, Nullable`1 timeout)
at Microsoft.Exchange.Management.RightsManagement.RMSValidator.ValidateEncryption(Stream& encryptedStream)
----------------------------------------

      OVERALL RESULT: FAIL

**Comment by ionise** [comment]
I have been taking the labs, I also saw this error I chose to ignore the problem and proceeded to the next exercises and things seemed to behave as though it worked all the same.

**Comment by vnvbadri** [comment]
Facing same issue, can some one help on this

**Comment by TesterTesterson1004** [comment]
It looks like the SC-400 flavor of this identical error was resolved via the addition of a -recipient switch at the end of the command.  

For this course, is there any specific -recipient that was intended?  In the case of SC-400, the same -recipient was used as the -Sender, so for this course the equivalent command to update into the instructions would presumably be:

 `Test-IRMConfiguration -Sender Holly@xxxxxZZZZZZ.onmicrosoft.com -Recipient Holly@xxxxxZZZZZZ.onmicrosoft.com`

**Comment by vnvbadri** [comment]
It worked for me thanks for your hep
